
name: Java CI with SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Or whichever version you require

    - name: Build with Maven and run SAST tools
      run: |
        mvn clean verify \
        && mvn spotbugs:spotbugs \
        && mvn pmd:pmd \
        && mvn checkstyle:check \
        && mvn org.owasp:dependency-check-maven:check \
        && mvn sonar:sonar \
        -Dsonar.host.url=https://sonarcloud.io/ \
        -Dsonar.login={{SONAR_TOKEN}} \
        -Dsonar.projectKey='findthehead'

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: target/

